version: '3.8'
services:
  app:
    build: .
    ports:
      - '30666:3000'
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prismadb?schema=public
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
