services:
  starboard:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.starboard.rule=Host(`stars.rjm.ie`)'
      - 'traefik.http.services.starboard.loadbalancer.server.port=3000'
      - 'traefik.http.routers.starboard.entrypoints=websecure'
      - 'traefik.http.routers.starboard.tls.certresolver=external-resolver'
      - 'external-service=true'
    build: .
    container_name: starboard
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prismadb?schema=public
      ADMIN_PASSWORD: changeme
      SHOP_ENABLED: 'true'
      STARBOARD_TITLE: 'Starboard'
      STARBOARD_SUBTITLE: 'Starharder'
    depends_on:
      - db
    networks:
      - traefik-external

  db:
    image: postgres:13
    container_name: starboard-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - traefik-external

networks:
  traefik-external:
    external: true

volumes:
  postgres-data:
